dist: trusty
#sudo: required
language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  # mark build as complete as soon as the versions that may not fail is finished
  fast_finish: true
  # these environment so far are allowed to fail
  allow_failures:
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"

notifications:
  slack:
    on_success: never

cache: pip

install:
    - pip install -U pip wheel setuptools
    - pip install -e .

script: 
    - pip freeze
    - cd masci_tools/tests/ && ./run_all.sh
after_success:
  # upload code coverage report
  - pip install codecov
  - codecov

git:
  depth: 3
