dist: trusty
#sudo: required
language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  # mark build as complete as soon as the versions that may not fail is finished
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
    - python: 3.8
      dist: xenial

notifications:
  slack:
    on_success: never

cache: pip

# does not work right now, probably because travis-ci org vs com ending
#before_install:
  #- openssl aes-256-cbc -K $encrypted_88038449450e_key -iv $encrypted_88038449450e_iv -in publish_to_pypi.sh.enc -out publish_to_pypi.sh -d

install:
  - pip install -U pip wheel setuptools
  - pip install pip==18.1
  - pip install -e .

script: 
  - pip freeze
  - cd masci_tools/tests/ && ./run_all.sh
after_success:
  # upload code coverage report
  - pip install codecov
  - codecov
  #- cd ../../ && pip install twine && ./publish_to_pypi.sh

git:
  depth: 3
