dist: trusty
#sudo: required
language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  # mark build as complete as soon as the versions that may not fail is finished
  fast_finish: true

notifications:
  slack:
    on_success: never

cache: pip

install:
    - pip install -U pip wheel setuptools
    - pip install -e .

script: 
    - pip freeze
    - cd masci_tools/tests/ && ./run_all.sh
after_success:
  # upload code coverage report
  - pip install codecov
  - codecov
  - openssl aes-256-cbc -K $encrypted_88038449450e_key -iv $encrypted_88038449450e_iv -in publish_to_pypi.sh.enc -out publish_to_pypi.sh -d
  - pip install twine && ./publish_to_pypi.sh

git:
  depth: 3
