[build-system]
requires = ["setuptools", "wheel"]

[tool.poetry]
name = "masci_tools"
version = "0.2.3-dev"
description = "Tools for Materials science. Vis contains wrapers of matplotlib functionality to visualalize common material science data. Plus wrapers of visualisation for aiida-fleur workflow nodes"
authors = ["Jens Bröder <j.broeder@fz-juelich.de>",
           "Philipp Rüssmann <p.ruessmann@fz-juelich.de>",
          ]
license = "MIT"
homepage = "https://github.com/JuDFTteam/masci-tools"
repository = "https://github.com/JuDFTteam/masci-tools"
documentation = "https://masci-tools.readthedocs.io"
keywords = ["material science",
            "plots",
            "visualization",
            "aiida",
            "dft"]
classifiers = ["Development Status :: 4 - Beta",
               "Intended Audience :: Science/Research",
               "License :: OSI Approved :: MIT License",
               "Programming Language :: Python :: 2.7",
               "Topic :: Scientific/Engineering :: Physics"]


[tool.poetry.dependencies]
python = "^2.7"
bumpversion = "^0.5.3"
numpy = "^1.16.2"
matplotlib = "^3.0.3"
h5py = "^2.9.0"
pytest-cov = "^2.6.1"
scipy = "^1.2.1"

