name: masci-stupro
channels:
  - conda-forge
  - anaconda
dependencies:
  - h5py
  - jupyter
  - notebook
  - jupyter_contrib_nbextensions
  - nodejs
  - jupyterlab
  - ipywidgets
  - ipympl
  - widgetsnbextension
  - ipyvolume
  - appmode
  - periodictable
  - tk
