name: masci-stupro
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.6.7
  - pip
  - future
  - logging
  - scipy
  - numpy
  - h5py
  - matplotlib
  - pytest-cov
  - jupyter
  - notebook
  - jupyter_contrib_nbextensions
  - nodejs
  - jupyterlab
  - ipywidgets
  - ipympl
  - widgetsnbextension
  - ipyvolume
  - appmode
  - periodictable
  - tk
  - voila
  - pip:
    - deprecated
    - fileupload
